### ISSUE TITLE
thanks for this elegant sample / one glitch with async

### ISSUE THREAD

**Issue by 8secz-johndpope** [JarodStreck/nodejs-aws-swf-demo#1]
in your code - your using
    "async": "^1.5.2",

the latest version is
    "async": "^3.2.0",

when I run it with latest async - it blows up with
```shell

/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:32
          throw err;
          ^

TypeError: cb is not a function
    at Response.<anonymous> (/Users/johndpope/Documents/8secondzWorkspace/coop/aws-swf/bootstrap.js:31:13)
    at Request.<anonymous> (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/Users/johndpope/Documents/8secondzWorkspace/coop/node_modules/aws-swf/node_modules/aws-sdk/lib/request.js:606:12)
```

I'll keep digging and if I find fix - will post PR.

**Comment by 8secz-johndpope** [comment]
this seems to be latest v3 documentation. 

https://caolan.github.io/async/v3/docs.html#auto
```javascript

async.auto({
    // this function will just be passed a callback
    readData: async.apply(fs.readFile, 'data.txt', 'utf-8'),
    showData: ['readData', function(results, cb) {
        // results.readData is the file's contents
        // ...
    }]
}, callback);

async.auto({
    get_data: function(callback) {
        console.log('in get_data');
        // async code to get some data
        callback(null, 'data', 'converted to array');
    },
    make_folder: function(callback) {
        console.log('in make_folder');
        // async code to create a directory to store a file in
        // this is run at the same time as getting the data
        callback(null, 'folder');
    },
    write_file: ['get_data', 'make_folder', function(results, callback) {
        console.log('in write_file', JSON.stringify(results));
        // once there is some data and the directory exists,
        // write the data to a file in the directory
        callback(null, 'filename');
    }],
    email_link: ['write_file', function(results, callback) {
        console.log('in email_link', JSON.stringify(results));
        // once the file is written let's email a link to it...
        // results.write_file contains the filename returned by write_file.
        callback(null, {'file':results.write_file, 'email':'user@example.com'});
    }]
}, function(err, results) {
    console.log('err = ', err);
    console.log('results = ', results);
});
```

**Comment by 8secz-johndpope** [comment]
npm install async@1.5.2 --save

**Comment by JarodStreck** [comment]
Thanks for the feedback, may update/fix if it interest you ! :)
